### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'ADmanage'

### ISSUE THREAD

**Issue by p0dalirius** [CobblePot59/ADcheck#1]
When starting the tool we get import errors:

```
# python3 ADcheck.min.py
Traceback (most recent call last):
  File "/workspace/ADcheck/ADcheck.min.py", line 1, in <module>
    from ADmanage import ADclient
ModuleNotFoundError: No module named 'ADmanage'
```

![image](https://github.com/CobblePot59/ADcheck/assets/79218792/965fde2f-e11a-4338-8fc9-b15b42b1101b)

This is because the structure of the dependencies is not a package and no `ADmanage.py` file is present at top level.

**Comment by CobblePot59** [comment]
I forgot ADmanage in my requirements.txt file, thank you ;)

**Comment by CobblePot59** [comment]
I forgot ADmanage in my requirements.txt file, thank you ;)
