### ISSUE TITLE
LDAPS

### ISSUE THREAD

**Issue by WiseLife42** [CobblePot59/ADcheck#3]
Salut l'équipe, 

Tout d'abord merci pour le partage et le temps passé pour dev le script !

Je rencontre le problème suivant :
![image](https://github.com/CobblePot59/ADcheck/assets/80531900/d2fc5359-87ba-4e67-b030-44cd83bbc8ad)

Cela est dû à l'activation de LDAPS via GPO,
Pensez-vous mettre en place un paramètre "--use-ldaps", comme le script "pywhisker" pour palier à cela ou avez-vous d'autre suggestion svp,
J'ai aperçu l'option "secure", mais ne fonctionne pas pour moi,

Merci

**Comment by CobblePot59** [comment]
When I added the pass the hash feature to my ADmanage library, the LDAPS connection was broken, it's functional again now. However, it's not possible to do pass the hash over LDAPS immediately. Update the dependencies in the requirements.txt file and add the -s option.
